### ISSUE TITLE
fix ControlSet path

### ISSUE THREAD

**Issue by hyuunnn** [EricZimmerman/RegistryPlugins#10]
I think ControlSet* looks better than ControlSet 0~5.
Before
<a href="https://github.com/EricZimmerman/RegistryPlugins/blob/master/RegistryPlugin.TimeZoneInformation/TimeZoneInfo.cs#L23">RegistryPlugin.TimeZoneInformation</a>
<a href="https://github.com/EricZimmerman/RegistryPlugins/blob/master/RegistryPlugin.DHCPNetworkHint/DHCPNetworkHint.cs#L25">RegistryPlugin.DHCPNetworkHint</a>
<a href="https://github.com/EricZimmerman/RegistryPlugins/blob/master/RegistryPlugin.AppCompatCache/AppCompat.cs#L25">RegistryPlugin.AppCompatCache</a>
<a href="https://github.com/EricZimmerman/RegistryPlugins/blob/master/RegistryPlugin.Services/Services.cs#L25">RegistryPlugin.Services</a>

After
<a href="https://github.com/hyuunnn/RegistryPlugins/blob/master/RegistryPlugin.USBSTOR/USBSTOR.cs#L24">RegistryPlugin.USBSTOR</a>

**Comment by EricZimmerman** [comment]
that was before i supported wildcards i think.

**Comment by EricZimmerman** [comment]
so, before i do this, can you make those changes in your fork, compile, test the new plugins, then do a PR? might as well since you did a PR for the new USBSTOR thing

**Comment by hyuunnn** [comment]
I have completed PR. #13

**Comment by EricZimmerman** [comment]
merged. nice work
