### ISSUE TITLE
RegistryPlugin.USBSTOR/ValuesOut.cs - Include DiskID

### ISSUE THREAD

**Issue by hirtj** [EricZimmerman/RegistryPlugins#24]
The inclusion of the DiskID for USBSTOR devices would be appreciated.

ValuesOut.cs - Line 36

**Comment by rathbuna** [comment]
@hirtj do you have a sample hive you could provide?

**Comment by hirtj** [comment]
Here is a sample hive:
https://drive.google.com/file/d/169s6wTk_SGi0TdxdjWNeEW5XAp80yisW/view?usp=sharing

**Comment by rathbuna** [comment]
So I'm understanding that you want the `DiskID` ValueName which is stored in the `ControlSet001\Enum\USBSTOR\Disk&Ven_EDGE&Prod_DiskGO_C2&Rev_5.00\1402192237285829014005&0\Device Parameters\Partmgr` Key Path added to this line in the Plugin outout: https://github.com/EricZimmerman/RegistryPlugins/blob/18e598af07a49ed984fec865ba868a3ec04da292/RegistryPlugin.USBSTOR/ValuesOut.cs#L36 

is that correct?

![image](https://user-images.githubusercontent.com/36825567/120679609-5adc6180-c467-11eb-955a-57ca1503bfd5.png)

**Comment by hirtj** [comment]
yes

**Comment by EricZimmerman** [comment]
![image](https://user-images.githubusercontent.com/4265254/120696949-22468300-c47b-11eb-93da-215c9198ee05.png)

done

check for update.
go forth and prosper
