### ISSUE TITLE
Possibly issue with parsing OpenSavePidMRU in RECmd and RegistryExplorer in latest version

### ISSUE THREAD

**Issue by mark-hallman** [EricZimmerman/RegistryPlugins#46]
** RECmd version # **
Reporting the version for REcmd and RegistryExplorer is difficult because for the last 12 - 18 months, the version displayed is 2.0.0.0, and there have been several updates in that time frame.  Here is the best I can do identifying the version.

Machine A  22.2  - referred to as “earlier version” in the screenshots
RECmd                Version: 2.0.0.0 Date Created  2022-10-02 
RegistryExplorer  Version 2.0.0.0 Date Created  2022-10-02 

Machine B 23.1 - referred to as the “latest version” in the screenshots
RECmd 	     Version: 2.0.0.0 Date Created 2023-01-17
RegistryExplorer  Version: 2.0.0.0 Date Created 2023-01-17

**Describe the bug**
This may be an intentional change that the author has made or possibly an inadvertent change in the code.  When the SANS FOR500 course VM was in QA review this week, one of the Registry labs was not producing the expected results for the OpenSavePidMRU key values shown in the ComDlg32 OpenSavePidMRU bookmark.

The tests I have run were done on two separate VMs; Machine A has an older version of EZTools.  Machine B has the latest version of EZTools. The data used in the lab is the rocba ntuser.dat from a KAPE Triage image.  I’ll try to upload that file. The data in both VMs are identical.  

The issue is that the new version (Machine B) of RECmd and RE drops some of the data that has historically been in the Absolute Path column. Specifically, the Absolute Path no longer shows the folders and file names, it only shows only the drive letter, colon, and three slashes.  In the lab, we are trying to find files that have “My Drive” in the Absolute Path, but on the screenshots, I am using  “F:\” has the filter to illustrate the issue.  See the screenshots below. 

**To Reproduce**

For each version of RE or RECmd do the following:

1. Load a clean ntuser.dat into RE or process with RECmd.  Both tools produce the same results
2. The recmd.exe command line used is provided below.
3. in RE, select the Bookmarks tab and select the ComDlg32 OpenSavePidMRU bookmark.
4. Filter the Absolute Path column on “F:\”
5. Review the values in the Absolute Path Column.

**Expected behavior**
The absolute Path should show the folder and file for each row in the table.

**Screenshots**

From Registry Explorer - Machine A
<img width="1819" alt="image" src="https://user-images.githubusercontent.com/16808320/219962460-4b49153b-2440-4292-ab5d-b8457fb01869.png">

From recmd.exe - UserActivity.reb - Machine A
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/16808320/219962499-9a06d7e4-9c19-4705-b97c-6562c55ad1b1.png">

From Registry Explorer - Machine B
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/16808320/219962626-6c8a4e49-b87a-4430-ad04-0d54caaee9ea.png">

From recmd.exe - UserActivity.reb - Machine B
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/16808320/219962806-b796f394-07fb-439a-b1ee-82f82950bba0.png">

**Comment by AndrewRathbun** [comment]
https://github.com/EricZimmerman/RegistryPlugins/blob/master/RegistryPlugin.OpenSavePidlMRU/OpenSavePidlMRU.cs hasn't changed in 5 years and https://github.com/EricZimmerman/RegistryPlugins/blob/master/RegistryPlugin.OpenSavePidlMRU/ValuesOut.cs hasn't changed in 2 years. The changes I made 2 years ago were purely cosmetic. The last substantial change to the Batch output was in 2019 by @EricZimmerman but I'm not seeing where something changed that affects the output to this degree. 

I'll keep doing some digging. I'll see if I have old plugin versions laying around. Or @mark-hallman if you can provide the OpenSavePidlMRU DLL from Machine A, that might be helpful.

**Comment by EricZimmerman** [comment]
Let's get the ntuser.dat mark is using and see what the actual data looks like.

**Comment by mark-hallman** [comment]
I posted the `ntuser.dat` that I have been testing with yesterday.  Look back up this thread for `ntuser.zip`.  Yes,  I will post the plugin from the system that is working correctly.

**Comment by mark-hallman** [comment]
[RegistryPlugin.OpenSavePidlMRU.dll.zip](https://github.com/EricZimmerman/RegistryPlugins/files/10794599/RegistryPlugin.OpenSavePidlMRU.dll.zip)

**Comment by mark-hallman** [comment]
FYI,  if I take the `RegistryPlugin.OpenSavePidlMRU.dll` from VM-A, the working system, and copy it to VM-B, the one that has issues,  VM-B will then work properly.

**Comment by AndrewRathbun** [comment]
Thanks @mark-hallman, if I don't get to this tonight, it'll happen tomorrow. Sorry for the delay!

**Comment by AndrewRathbun** [comment]
I did some work on this tonight and communicated my findings with Eric. He'll circle back when he can with next steps.

**Comment by mark-hallman** [comment]
Thanks, Andrew.  We appreciate both of you for all the time you dedicate to developing the excellent tools, scripts, and other resources you provide to the DFIR community for free!!

**Comment by mark-hallman** [comment]
Andrew / Eric,  Any word on a fix for this issue?

**Comment by EricZimmerman** [comment]
i see the issue. someone did a PR and introduced a bug. fixing now

**Comment by EricZimmerman** [comment]
![image](https://user-images.githubusercontent.com/4265254/221916188-011ca79a-4fff-4c01-838c-261908c1b6ff.png)

**Comment by EricZimmerman** [comment]
updating plugins and tools, then will push out
