### ISSUE TITLE
RECmd/RegistryExplorer Not Loading Plugin DLLs

### ISSUE THREAD

**Issue by h0riz0nz** [EricZimmerman/RegistryPlugins#9]
I've replicated this issue across two separate Win10 hosts for both RegistryExplorer and RECmd. Below is an example output.

Win10 Build: 18363

`C:\Users\<Username>\Triage\RegistryExplorer>RECmd.exe -f c:\Users\<Username>\NTUSER.DAT --sa "userassist"
RECmd version 1.5.2.0

Author: Eric Zimmerman (saericzimmerman@gmail.com)
https://github.com/EricZimmerman/RECmd

Note: Enclose all strings containing spaces (and all RegEx) with double quotes

Command line: -f c:\Users\<Username>\NTUSER.DAT --sa userassist

Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.7-ZipHistory.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.Adobe.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.AppCompatCache.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.AppCompatFlags.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.Ares.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.BamDam.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.BluetoothServicesBthPort.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.CIDSizeMRU.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.DHCPNetworkHint.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.FileExts.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.FirstFolder.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.JumplistData.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.KnownNetworks.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.LastVisitedMRU.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.LastVisitedPidlMRU.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.MountedDevices.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.OfficeMRU.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.OpenSaveMRU.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.OpenSavePidlMRU.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.RecentApps.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.RecentDocs.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.RunMRU.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.SAM.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.Services.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.SyscacheObjectTable.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.Taskband.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.TaskFlowShellActivities.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.TerminalServerClient.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.TimeZoneInformation.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.TrustedDocuments.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.TypedURLs.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.UserAssist.dll
Error loading plugin: C:\Users\<Username>\Triage\RegistryExplorer\Plugins\RegistryPlugin.WordWheelQuery.dll

Processing hive 'c:\Users\<Username>\NTUSER.DAT'
'c:\Users\<Username>\NTUSER.DAT' is in use. Rerouting...

Two transaction logs found. Determining primary log...
Primary log: c:\Users\<Username>\ntuser.dat.LOG2, secondary log: c:\Users\<Username>\ntuser.dat.LOG1
Replaying log file: c:\Users\<Username>\ntuser.dat.LOG2
Replaying log file: c:\Users\<Username>\ntuser.dat.LOG1
At least one transaction log was applied. Sequence numbers have been updated to 0x1AFEA. New Checksum: 0x1DE42454
        Found 1 search hit in 'c:\Users\<Username>\NTUSER.DAT'
        Key: 'SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\UserAssist'`

**Comment by EricZimmerman** [comment]
Don't use Windows to unzip, like the download page says. 

Delete the folder and then re extract using seven zip

**Comment by h0riz0nz** [comment]
Thank you!
